name: towncrier

on: 
  workflow_dispatch:
  workflow_call:
  # push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Build
        run: |
          poetry install --with=dev
          source .venv/bin/activate
          towncrier build --yes
          git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: master
          branch: new-version
          commit-message: "Bumped the version"
          title: "Bumped the version"
          body: "Bumped the version"
          reviewers: kornpow
